# Generated by Django 5.2.4 on 2025-08-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_eventplan_event_plan_historicalevent_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplan',
            name='time_of_day',
            field=models.CharField(default='12:00', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaleventplan',
            name='time_of_day',
            field=models.CharField(default='12:00', max_length=5),
            preserve_default=False,
        ),
    ]
