# Generated by Django 5.2.4 on 2025-08-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_created_by_historicalevent_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
