# Generated by Django 5.2.4 on 2025-07-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='source',
        ),
        migrations.AddField(
            model_name='historicalsource',
            name='cron_expression',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalsource',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalsource',
            name='last_run',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalsource',
            name='next_run',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='cron_expression',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_run',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='next_run',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalSchedule',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
