# Generated by Django 5.2.4 on 2025-07-15 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringkey',
            name='ring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ring.ring'),
        ),
        migrations.AlterField(
            model_name='ringkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
