# Generated by Django 5.2.4 on 2025-07-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ring', '0002_alter_ringkey_ring_alter_ringkey_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ring',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
